name: MinigamePlugin
version: '${project.version}'
main: mod.minigameplugin.MinigamePlugin
api-version: '1.21'

commands:
  readitemorblockdata:
    description: Lets you read the data of a item or block
    usage: /readitemorblockdata <setting>
    permission: lifestealSMP.admin
    default: op
  setview:
    description: Set render and sim distance
    usage: /setview <render> <sim>
    permission: lifestealSMP.admin
    default: op
  zombiegame:
    description: Start and stop zombie game
    usage: /zombiegame <start or stop>
    permission: lifestealSMP.admin
    default: op
  givezombiesitem:
    description: Gives items from the zombie game
    usage: /givezombiesitem <item>
    permission: lifestealSMP.admin
    default: op
  givehealthpack:
    description: Gives a health pack
    usage: /givehealthpack
    permission: lifestealSMP.admin
    default: op
  iamafuckingshowoff:
    description: Displays to everyone or a single player what you have
    usage: /iamafuckingshowoff <player>