name: MinigamePlugin
version: '${project.version}'
main: mod.minigameplugin.MinigamePlugin
api-version: '1.21'

commands:
  readitemorblockdata:
    description: Lets you read the data of a item or block
    usage: /readitemorblockdata <setting>
    permission: lifestealSMP.admin
    default: op
  setview:
    description: Set render and sim distance
    usage: /setview <render> <sim>
    permission: lifestealSMP.admin
    default: op